title: Jonghyun Bae
logo: /assets/img/bjh.jpg
description: E-mail - bnbbkr (at) gmail (dot) com / jonghbae (at) snu (dot) ac (dot) kr
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
