title: Jonghyun Bae
logo: /assets/img/bjh.jpg
description: Minimal is a theme for GitHub Pages.
mail: E-mail: bnbbkr (at) gmail (dot) com
linkedin: Linkedin: https://www.linkedin.com/in/jonghyun-bae-a4399911a/
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
